// Code generated by hertz generator.

package main

import (
	"douyin/biz/mw"
	"douyin/dal/db"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	db.Init()
	mw.InitJWT()
}

func main() {
	h := server.Default(
		server.WithHostPorts("192.168.18.6:30000"),
		server.WithExitWaitTime(0),
	)

	Init()
	register(h)
	h.Spin()
}
