// Code generated by hertz generator.

package api

import (
	"context"

	"douyin/biz/model/api"
	"douyin/biz/service"
	"douyin/pkg/constant"
	"douyin/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FavoriteVideo .
// @router /douyin/favorite/action/ [POST]
func FavoriteVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DouyinFavoriteActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	hlog.Info("handler.favorite_service.FavoriteVideo Request:", req)
	userID := c.GetUint64(constant.IdentityKey)
	hlog.Info("handler.favorite_service.FavoriteVideo GetUserID:", userID)
	var resp *api.DouyinFavoriteActionResponse
	if req.ActionType == constant.Favorite {
		resp, err = service.FavoriteVideo(userID, uint64(req.VideoID))
	} else if req.ActionType == constant.CancelFavorite {
		resp, err = service.CancelFavoriteVideo(userID, uint64(req.VideoID))
	} else {
		err = errno.UserRequestParameterError
		hlog.Error("handler.favorite_service.FavoriteVideo err:", err.Error())
	}

	if err != nil {
		errNo := errno.ConvertErr(err)
		c.JSON(consts.StatusOK, &api.DouyinFavoriteActionResponse{
			StatusCode: errNo.ErrCode,
			StatusMsg:  &errNo.ErrMsg,
		})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetFavoriteList .
// @router /douyin/favorite/list/ [GET]
func GetFavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DouyinFavoriteListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	hlog.Info("handler.favorite_service.GetFavoriteList Request:", req)
	userID := c.GetUint64(constant.IdentityKey)
	hlog.Info("handler.favorite_service.GetFavoriteList GetUserID:", userID)
	resp, err := service.FavoriteList(userID, uint64(req.UserID))
	if err != nil {
		errNo := errno.ConvertErr(err)
		c.JSON(consts.StatusOK, &api.DouyinFavoriteListResponse{
			StatusCode: errNo.ErrCode,
			StatusMsg:  &errNo.ErrMsg,
		})
		return
	}

	c.JSON(consts.StatusOK, resp)
}
