// Code generated by hertz generator.

package api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"

	api "douyin/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PublishAction .
// @router /douyin/publish/action/ [POST]
func PublishAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DouyinPublishActionRequest
	hlog.Infof("%#v de", req)

	file, err := c.FormFile("data")
	if err != nil {
		hlog.Info("error")
		hlog.Info(err)
	}
	hlog.Infof("%#v", file.Filename)

	err = c.BindAndValidate(&req)
	//if err != nil {
	//	c.String(consts.StatusBadRequest, err.Error())
	//	return
	//}

	resp := new(api.DouyinPublishActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetPublishVideos .
// @router /douyin/publish/list/ [GET]
func GetPublishVideos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DouyinPublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	hlog.Infof("%#v", req)

	var followCount int64 = 3
	var followerCount int64 = 3
	u := &api.User{
		ID:            1,
		Name:          "name",
		FollowCount:   &followCount,
		FollowerCount: &followerCount,
		IsFollow:      false,
		Avatar:        "https://picture-bucket-01.oss-cn-beijing.aliyuncs.com/DouYin/cover/cover01.png",
	}

	videos := make([]*api.Video, 0)
	videos = append(videos, &api.Video{
		ID:            1,
		Author:        u,
		PlayURL:       "https://picture-bucket-01.oss-cn-beijing.aliyuncs.com/DouYin/video/video01.mp4",
		CoverURL:      "https://picture-bucket-01.oss-cn-beijing.aliyuncs.com/DouYin/cover/cover01.png",
		FavoriteCount: 2,
		CommentCount:  2,
		IsFavorite:    false,
		Title:         "video01",
	})
	resp := &api.DouyinPublishListResponse{
		StatusCode: 0,
		StatusMsg:  nil,
		VideoList:  videos,
	}

	c.JSON(consts.StatusOK, resp)
}
