// Code generated by Validator v0.1.4. DO NOT EDIT.

package api

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *DouyinResponse) IsValid() error {
	return nil
}
func (p *DouyinCommentActionRequest) IsValid() error {
	if p.VideoID <= int64(0) {
		return fmt.Errorf("field VideoID gt rule failed, current value: %v", p.VideoID)
	}
	_src := []int8{int8(1), int8(2)}
	var _exist bool
	for _, src := range _src {
		if p.ActionType == int8(src) {
			_exist = true
			break
		}
	}
	if !_exist {
		return fmt.Errorf("field ActionType in rule failed, current value: %v", p.ActionType)
	}
	if p.CommentText != nil {
		if len(*p.CommentText) < int(1) {
			return fmt.Errorf("field CommentText min_len rule failed, current value: %d", len(*p.CommentText))
		}
		if len(*p.CommentText) > int(255) {
			return fmt.Errorf("field CommentText max_len rule failed, current value: %d", len(*p.CommentText))
		}
	}
	if p.CommentID != nil {
		if *p.CommentID <= int64(0) {
			return fmt.Errorf("field CommentID gt rule failed, current value: %v", *p.CommentID)
		}
	}
	return nil
}
func (p *DouyinCommentActionResponse) IsValid() error {
	if p.Comment != nil {
		if err := p.Comment.IsValid(); err != nil {
			return fmt.Errorf("filed Comment not valid, %w", err)
		}
	}
	return nil
}
func (p *DouyinCommentListRequest) IsValid() error {
	if p.VideoID <= int64(0) {
		return fmt.Errorf("field VideoID gt rule failed, current value: %v", p.VideoID)
	}
	return nil
}
func (p *DouyinCommentListResponse) IsValid() error {
	return nil
}
func (p *Comment) IsValid() error {
	if p.User != nil {
		if err := p.User.IsValid(); err != nil {
			return fmt.Errorf("filed User not valid, %w", err)
		}
	}
	return nil
}
func (p *CommentUser) IsValid() error {
	return nil
}
func (p *User) IsValid() error {
	return nil
}
func (p *DouyinFavoriteActionRequest) IsValid() error {
	if p.VideoID <= int64(0) {
		return fmt.Errorf("field VideoID gt rule failed, current value: %v", p.VideoID)
	}
	_src := []int8{int8(1), int8(2)}
	var _exist bool
	for _, src := range _src {
		if p.ActionType == int8(src) {
			_exist = true
			break
		}
	}
	if !_exist {
		return fmt.Errorf("field ActionType in rule failed, current value: %v", p.ActionType)
	}
	return nil
}
func (p *DouyinFavoriteActionResponse) IsValid() error {
	return nil
}
func (p *DouyinFavoriteListRequest) IsValid() error {
	if p.UserID <= int64(0) {
		return fmt.Errorf("field UserID gt rule failed, current value: %v", p.UserID)
	}
	return nil
}
func (p *DouyinFavoriteListResponse) IsValid() error {
	return nil
}
func (p *Video) IsValid() error {
	if p.Author != nil {
		if err := p.Author.IsValid(); err != nil {
			return fmt.Errorf("filed Author not valid, %w", err)
		}
	}
	return nil
}
func (p *DouyinFeedRequest) IsValid() error {
	return nil
}
func (p *DouyinFeedResponse) IsValid() error {
	return nil
}
func (p *DouyinFeedFollowRequest) IsValid() error {
	return nil
}
func (p *DouyinFeedFollowResponse) IsValid() error {
	return nil
}
func (p *DouyinFeedFriendRequest) IsValid() error {
	return nil
}
func (p *DouyinFeedFriendResponse) IsValid() error {
	return nil
}
func (p *DouyinMessageChatRequest) IsValid() error {
	if p.ToUserID <= int64(0) {
		return fmt.Errorf("field ToUserID gt rule failed, current value: %v", p.ToUserID)
	}
	return nil
}
func (p *DouyinMessageChatResponse) IsValid() error {
	return nil
}
func (p *Message) IsValid() error {
	return nil
}
func (p *DouyinMessageActionRequest) IsValid() error {
	if p.ToUserID <= int64(0) {
		return fmt.Errorf("field ToUserID gt rule failed, current value: %v", p.ToUserID)
	}
	_src := []int8{int8(1)}
	var _exist bool
	for _, src := range _src {
		if p.ActionType == int8(src) {
			_exist = true
			break
		}
	}
	if !_exist {
		return fmt.Errorf("field ActionType in rule failed, current value: %v", p.ActionType)
	}
	if len(p.Content) < int(1) {
		return fmt.Errorf("field Content min_len rule failed, current value: %d", len(p.Content))
	}
	if len(p.Content) > int(255) {
		return fmt.Errorf("field Content max_len rule failed, current value: %d", len(p.Content))
	}
	return nil
}
func (p *DouyinMessageActionResponse) IsValid() error {
	return nil
}
func (p *DouyinPublishActionRequest) IsValid() error {
	if len(p.Title) < int(1) {
		return fmt.Errorf("field Title min_len rule failed, current value: %d", len(p.Title))
	}
	if len(p.Title) > int(63) {
		return fmt.Errorf("field Title max_len rule failed, current value: %d", len(p.Title))
	}
	return nil
}
func (p *DouyinPublishActionResponse) IsValid() error {
	return nil
}
func (p *DouyinPublishListRequest) IsValid() error {
	if p.UserID <= int64(0) {
		return fmt.Errorf("field UserID gt rule failed, current value: %v", p.UserID)
	}
	return nil
}
func (p *DouyinPublishListResponse) IsValid() error {
	return nil
}
func (p *DouyinRelationActionRequest) IsValid() error {
	if p.ToUserID <= int64(0) {
		return fmt.Errorf("field ToUserID gt rule failed, current value: %v", p.ToUserID)
	}
	_src := []int8{int8(1), int8(2)}
	var _exist bool
	for _, src := range _src {
		if p.ActionType == int8(src) {
			_exist = true
			break
		}
	}
	if !_exist {
		return fmt.Errorf("field ActionType in rule failed, current value: %v", p.ActionType)
	}
	return nil
}
func (p *DouyinRelationActionResponse) IsValid() error {
	return nil
}
func (p *DouyinRelationFollowListRequest) IsValid() error {
	if p.UserID <= int64(0) {
		return fmt.Errorf("field UserID gt rule failed, current value: %v", p.UserID)
	}
	return nil
}
func (p *DouyinRelationFollowListResponse) IsValid() error {
	return nil
}
func (p *FollowUser) IsValid() error {
	return nil
}
func (p *DouyinRelationFollowerListRequest) IsValid() error {
	if p.UserID <= int64(0) {
		return fmt.Errorf("field UserID gt rule failed, current value: %v", p.UserID)
	}
	return nil
}
func (p *DouyinRelationFollowerListResponse) IsValid() error {
	return nil
}
func (p *FollowerUser) IsValid() error {
	return nil
}
func (p *DouyinRelationFriendListRequest) IsValid() error {
	if p.UserID <= int64(0) {
		return fmt.Errorf("field UserID gt rule failed, current value: %v", p.UserID)
	}
	return nil
}
func (p *DouyinRelationFriendListResponse) IsValid() error {
	return nil
}
func (p *FriendUser) IsValid() error {
	return nil
}
func (p *DouyinUserRegisterRequest) IsValid() error {
	if len(p.Username) < int(2) {
		return fmt.Errorf("field Username min_len rule failed, current value: %d", len(p.Username))
	}
	if len(p.Username) > int(32) {
		return fmt.Errorf("field Username max_len rule failed, current value: %d", len(p.Username))
	}
	if len(p.Password) < int(6) {
		return fmt.Errorf("field Password min_len rule failed, current value: %d", len(p.Password))
	}
	if len(p.Password) > int(32) {
		return fmt.Errorf("field Password max_len rule failed, current value: %d", len(p.Password))
	}
	return nil
}
func (p *DouyinUserRegisterResponse) IsValid() error {
	return nil
}
func (p *DouyinUserLoginRequest) IsValid() error {
	if len(p.Username) < int(2) {
		return fmt.Errorf("field Username min_len rule failed, current value: %d", len(p.Username))
	}
	if len(p.Username) > int(32) {
		return fmt.Errorf("field Username max_len rule failed, current value: %d", len(p.Username))
	}
	if len(p.Password) < int(6) {
		return fmt.Errorf("field Password min_len rule failed, current value: %d", len(p.Password))
	}
	if len(p.Password) > int(32) {
		return fmt.Errorf("field Password max_len rule failed, current value: %d", len(p.Password))
	}
	return nil
}
func (p *DouyinUserLoginResponse) IsValid() error {
	return nil
}
func (p *DouyinUserRequest) IsValid() error {
	if p.UserID <= int64(0) {
		return fmt.Errorf("field UserID gt rule failed, current value: %v", p.UserID)
	}
	return nil
}
func (p *DouyinUserResponse) IsValid() error {
	if p.User != nil {
		if err := p.User.IsValid(); err != nil {
			return fmt.Errorf("filed User not valid, %w", err)
		}
	}
	return nil
}
func (p *UserInfo) IsValid() error {
	return nil
}
